openapi: "3.0.2"
info:
  title: OpenAPI definition
  version: v0
#servers:
#  - url: http://localhost:8080
#    description: Generated server url
paths:
  /v1.0/wizards:
    get:
      tags:
        - Wizard-controller
      operationId: getAllWizards
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: array
            items:
              type: integer
      responses:
        "200":
          description: Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Wizard"
components:
  schemas:
    Wizard:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        gender:
          type: string
        role:
          type: string