version: '3.8'
services:
  postgresql:
    image: postgres:14.6
    container_name: postgresql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - hogwarts-micro-services-network
    ports:
      - "5432:5432"
  wizard-service:
    image: hogwarts-wizard-service:0.0.1
    container_name: wizard-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/hogwarts?currentSchema=wizard
    depends_on:
      - postgresql
    networks:
      - hogwarts-micro-services-network
    ports:
      - "8081:8080"
  subject-service:
    image: hogwarts-subject-service:0.0.1
    container_name: subject-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/hogwarts?currentSchema=subject
      - FEIGN_CLIENT_WIZARD_URL=http://wizard-service:8080
    depends_on:
      - postgresql
    networks:
      - hogwarts-micro-services-network
    ports:
      - "8080:8080"
networks:
  hogwarts-micro-services-network:

